language: node_js
node_js:
  - "10"
before_script:
  - "export CHOME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - "node_modules/protractor/bin/webdriver-manager update"
  
install:
  - npm install
script:
  - grunt protractor:test